# Docker Compose for Project questMe
version: '3.9'

services:
  # Angular Frontend
  angular-frontend:
    container_name: angular-frontend
    build: ./admin-interface
    ports:
      - 4200:4200
    networks:
      - frontend

  # Chat Server nodejs
  node-server:
    container_name: nodewebapp
    build: ./node-web-server
    environment:
      - MONGODB_CONNSTRING=mongodb://mongodb
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - mongodb
      - angular-frontend
    networks:
      - app

  # Database in mongoDB
  mongodb:
    container_name: mongodb
    build: ./mongodb
    environment:
      - MONGO_INITDB_DATABASE=corpus
    volumes:
      - .db-data:/data/db # docker stores in folder questMe
      #- db-data:/data/db # shared Volume for docker container
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js
    restart: always
    ports:
      - 27017:27017
    networks:
      app:
        aliases:
          - database

  # Keycloak Authentication
  keycloak:
    container_name: keycloak
    build: ./keycloak-server
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    restart: always
    depends_on:
      - angular-frontend
    ports:
      - 8080:8080
    networks:
      app:

networks:
  app:
    driver: bridge
  frontend: null
  
#volumes:
# db-data: